= Harpseal API Docs
Harseal API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[퀴즈-API]]
== 퀴즈 API

[[퀴즈-목록-조회]]
=== 퀴즈 목록 조회
operation::퀴즈 목록 조회[snippets='http-request,query-parameters,request-fields,http-response,response-fields']

[[퀴즈-단일-조회]]
=== 퀴즈 단일 조회
operation::단일 퀴즈 조회[snippets='http-request,path-parameters,http-response,response-fields']

[[퀴즈-생성]]
=== 퀴즈 생성
operation::퀴즈 생성[snippets='http-request,request-part-form-body,request-part-form-fields,http-response']

[[퀴즈-삭제]]
=== 퀴즈 삭제
operation::퀴즈 삭제[snippets='http-request,request-fields,http-response']

- 삭제 성공 시 퀴즈 목록으로 이동

[[퀴즈-좋아요-증가]]
=== 퀴즈 좋아요 증가
operation::퀴즈 좋아요 증가[snippets='http-request,path-parameters,http-response']

[[퀴즈-문제-등록]]
=== 퀴즈 문제 등록
operation::퀴즈 문제 등록[snippets='http-request,path-parameters,request-part-form-body,request-part-form-fields,http-response,response-fields']

[[퀴즈-수정]]
=== 퀴즈 수정
operation::퀴즈 수정[snippets='http-request,path-parameters,request-part-form-body,request-part-form-fields']

